CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int NOT NULL,
  "email" varchar(40) NOT NULL,
  "password" varchar(10) NOT NULL,
  "age_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tilte_id" int NOT NULL,
  "description" varchar(30) NOT NULL,
  "level_id" int NOT NULL,
  "teacher_id" int NOT NULL
);

CREATE TABLE "Courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tilte_id" int NOT NULL,
  "url" varchar(30) NOT NULL
);

CREATE TABLE "Roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student" varchar(30) NOT NULL,
  "teacher" varchar(30) NOT NULL,
  "admin" varchar(30) NOT NULL
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "programacion" varchar(20) NOT NULL
);

CREATE TABLE "Levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(20) NOT NULL
);

CREATE TABLE "Titles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "Ages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Age" int NOT NULL
);

ALTER TABLE "Users" ADD FOREIGN KEY ("age_id") REFERENCES "Ages" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("tilte_id") REFERENCES "Titles" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("level_id") REFERENCES "Levels" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "Roles" ("id");

ALTER TABLE "Courses_video" ADD FOREIGN KEY ("tilte_id") REFERENCES "Titles" ("id");

ALTER TABLE "Users" ADD FOREIGN KEY ("role_id") REFERENCES "Roles" ("id");

ALTER TABLE "Titles" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("id");

ALTER TABLE "Users" ADD FOREIGN KEY ("course_id") REFERENCES "Courses" ("id");
